modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="create_chemical_industry"
version="${file.jarVersion}"
displayName="Create Chemical Industry Mod"
logoFile="create_chemical_industry.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
'''

[[dependencies.create_chemical_industry]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_chemical_industry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

